import { ArrowLeft, ArrowRight, Check, ChevronLeft, Clock3, LockKeyhole, MessageCircle, ShieldCheck, Video, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import SiteHeader from "@/components/SiteHeader";
import { emptyBooking, formatBRL, formatDateLong, formatDateShort, getAvailableDates, getAvailableTimes, getModalityLabel, getReading, modalityDetails, readings, type BookingState, type Modality } from "@/lib/content";
import { getStoredUtms, track } from "@/lib/analytics";
import { createMockBookingPreview, type BookingPreview } from "@/services/bookingService";

const steps = ["Leitura", "Modalidade", "Data e horário", "Seus dados", "Pagamento"];

export default function Booking() {
  const [location, setLocation] = useLocation();
  const params = useMemo(() => new URLSearchParams(location.split("?")[1] ?? ""), [location]);
  const initialReading = params.get("servico") ?? readings[0].slug;
  const [step, setStep] = useState(0);
  const [booking, setBooking] = useState<BookingState>({ ...emptyBooking, readingSlug: initialReading });
  const [confirmed, setConfirmed] = useState(false);
  const [bookingPreview, setBookingPreview] = useState<BookingPreview | null>(null);
  const [errors, setErrors] = useState<string[]>([]);
  const dates = useMemo(() => getAvailableDates(), []);
  const reading = getReading(booking.readingSlug);
  const times = useMemo(() => getAvailableTimes(reading), [reading]);

  const update = <K extends keyof BookingState>(key: K, value: BookingState[K]) => setBooking((current) => ({ ...current, [key]: value }));
  const next = () => {
    setErrors([]);
    if (step === 0) track("select_service", { service: booking.readingSlug });
    if (step === 1 && !booking.modality) return setErrors(["Escolha uma modalidade para continuar."]);
    if (step === 2 && (!booking.date || !booking.time)) return setErrors(["Escolha um dia e um horário disponíveis."]);
    if (step === 3) {
      const nextErrors = [];
      if (!booking.name.trim()) nextErrors.push("Informe seu nome.");
      if (!booking.email.includes("@")) nextErrors.push("Informe um e-mail válido.");
      if (!booking.whatsapp.trim()) nextErrors.push("Informe seu WhatsApp.");
      if (nextErrors.length) return setErrors(nextErrors);
      track("begin_checkout", { service: reading.slug, modality: booking.modality, utms: getStoredUtms() });
    }
    setStep((current) => Math.min(current + 1, steps.length - 1));
  };
  const back = () => { setErrors([]); setStep((current) => Math.max(current - 1, 0)); };
  const confirmDemo = () => {
    const preview = createMockBookingPreview(booking, reading);
    setBookingPreview(preview);
    track("purchase", { status: preview.paymentStatus, service: reading.slug, utms: preview.utms });
    setConfirmed(true);
  };

  if (confirmed && bookingPreview) return <Confirmation preview={bookingPreview} setLocation={setLocation} />;

  return <div className="site-shell booking-shell"><SiteHeader /><main className="booking-page section-pad"><div className="booking-heading"><Link href="/" className="back-link"><ChevronLeft size={15} /> Voltar ao início</Link><span className="section-kicker">AGENDAMENTO · AMERICA/SAO_PAULO</span><h1>Um encontro começa<br /><em>com espaço.</em></h1></div><div className="stepper" aria-label="Etapas do agendamento">{steps.map((item, index) => <div className={`stepper-item ${index === step ? "active" : ""} ${index < step ? "done" : ""}`} key={item}><span>{index < step ? <Check size={13} /> : `0${index + 1}`}</span><label>{item}</label></div>)}</div><div className="booking-layout"><section className="booking-card">{step === 0 && <ReadingStep selected={booking.readingSlug} onSelect={(value) => update("readingSlug", value)} />}{step === 1 && <ModalityStep reading={reading} selected={booking.modality} onSelect={(value) => { update("modality", value); track("select_modality", { modality: value }); }} />}{step === 2 && <DateStep dates={dates} times={times} selectedDate={booking.date} selectedTime={booking.time} onDate={(value) => { update("date", value); update("time", ""); track("select_date", { date: value }); }} onTime={(value) => { update("time", value); track("select_time", { time: value }); }} />}{step === 3 && <DetailsStep booking={booking} update={update} />}{step === 4 && <PaymentStep booking={booking} reading={reading} onConfirm={confirmDemo} />}{errors.length > 0 && <div className="form-errors" role="alert">{errors.map((error) => <p key={error}>{error}</p>)}</div>}{step < 4 && <div className="booking-actions"><button className="button button-ghost" onClick={back} disabled={step === 0}><ArrowLeft size={15} /> Voltar</button><button className="button button-primary" onClick={next}>Continuar <ArrowRight size={15} /></button></div>}</section><aside className="booking-summary"><span className="section-kicker">RESUMO</span><div className="summary-symbol">✦</div><h2>{reading.name}</h2><p>{reading.description}</p><div className="summary-line"><span>Valor inicial</span><strong>{formatBRL(reading.price)}</strong></div>{booking.modality && <div className="summary-line"><span>Modalidade</span><strong>{getModalityLabel(booking.modality)}</strong></div>}{booking.date && <div className="summary-line"><span>Quando</span><strong>{new Date(`${booking.date}T12:00:00`).toLocaleDateString("pt-BR")} · {booking.time}</strong></div>}<div className="summary-note"><LockKeyhole size={15} /> Seus dados são tratados com privacidade.</div></aside></div></main></div>;
}

function ReadingStep({ selected, onSelect }: { selected: string; onSelect: (value: string) => void }) { return <div><StepIntro eyebrow="01 · LEITURA" title="O que você quer olhar?" copy="Comece escolhendo o formato que melhor acolhe a sua pergunta." /><div className="booking-options">{readings.map((reading) => <button className={`booking-option ${selected === reading.slug ? "selected" : ""}`} key={reading.slug} onClick={() => onSelect(reading.slug)}><span><strong>{reading.name}</strong><small>{reading.eyebrow}</small></span><span className="option-price">{formatBRL(reading.price)}</span></button>)}</div></div>; }
function ModalityStep({ reading, selected, onSelect }: { reading: ReturnType<typeof getReading>; selected: Modality | null; onSelect: (value: Modality) => void }) { return <div><StepIntro eyebrow="02 · MODALIDADE" title="Como prefere conversar?" copy="Escolha a forma de presença que combina com este momento." /><div className="booking-options">{reading.availableModalities.map((modality) => <button className={`booking-option modality-option ${selected === modality ? "selected" : ""}`} key={modality} onClick={() => onSelect(modality)}><span><strong>{modalityDetails[modality].name}</strong><small>{modalityDetails[modality].description}</small></span><span className="modality-icon">{modality === "video" ? <Video size={18} /> : modality === "voice" ? <MessageCircle size={18} /> : <MessageCircle size={18} />}</span></button>)}</div><p className="quiet-note"><Clock3 size={15} /> Sem cobrança por minuto. O valor exibido é o valor da consulta.</p></div>; }
function DateStep({ dates, times, selectedDate, selectedTime, onDate, onTime }: { dates: Date[]; times: string[]; selectedDate: string; selectedTime: string; onDate: (value: string) => void; onTime: (value: string) => void }) { return <div><StepIntro eyebrow="03 · DATA E HORÁRIO" title="Encontre um momento." copy="Mostramos apenas horários disponíveis. O fuso considerado é America/Sao_Paulo." /><div className="date-picker"><div className="date-list">{dates.map((date) => { const key = date.toISOString().slice(0, 10); return <button key={key} className={`date-option ${selectedDate === key ? "selected" : ""}`} onClick={() => onDate(key)}><span>{date.toLocaleDateString("pt-BR", { weekday: "short" }).replace(".", "")}</span><strong>{formatDateShort(date)}</strong></button>; })}</div>{selectedDate ? <div className="time-list"><span className="section-kicker">HORÁRIOS EM {formatDateLong(new Date(`${selectedDate}T12:00:00`))}</span><div>{times.map((time) => <button key={time} className={`time-option ${selectedTime === time ? "selected" : ""}`} onClick={() => onTime(time)}>{time}</button>)}</div></div> : <p className="quiet-note">Escolha um dia para ver os horários disponíveis.</p>}</div></div>; }
function DetailsStep({ booking, update }: { booking: BookingState; update: <K extends keyof BookingState>(key: K, value: BookingState[K]) => void }) { return <div><StepIntro eyebrow="04 · SEUS DADOS" title="Como podemos te encontrar?" copy="Só pedimos o necessário para organizar o encontro. O contexto inicial é opcional." /><div className="details-form"><label>Nome<input value={booking.name} onChange={(event) => update("name", event.target.value)} placeholder="Como você gostaria de ser chamada?" /></label><label>E-mail<input type="email" value={booking.email} onChange={(event) => update("email", event.target.value)} placeholder="voce@exemplo.com" /></label><label>WhatsApp<input value={booking.whatsapp} onChange={(event) => update("whatsapp", event.target.value)} placeholder="(00) 00000-0000" /></label><label>Pergunta ou contexto inicial <span>opcional</span><textarea value={booking.context} onChange={(event) => update("context", event.target.value)} placeholder="Se quiser, conte brevemente o que te traz até aqui." rows={4} /></label><label className="consent-line"><input type="checkbox" required /><span>Li e concordo com os <a href="#">Termos</a> e a <a href="#">Política de Privacidade</a>.</span></label></div></div>; }
function PaymentStep({ booking, reading, onConfirm }: { booking: BookingState; reading: ReturnType<typeof getReading>; onConfirm: () => void }) { return <div><StepIntro eyebrow="05 · PAGAMENTO" title="Tudo certo para continuar?" copy="A integração Mercado Pago será conectada quando as credenciais estiverem disponíveis." /><div className="payment-review"><div><span>Leitura</span><strong>{reading.name}</strong></div><div><span>Encontro</span><strong>{booking.modality ? getModalityLabel(booking.modality) : "—"} · {booking.date ? new Date(`${booking.date}T12:00:00`).toLocaleDateString("pt-BR") : "—"} · {booking.time || "—"}</strong></div><div><span>Valor total</span><strong className="payment-total">{formatBRL(reading.price)}</strong></div></div><div className="mock-payment"><WalletCards size={20} /><div><strong>Pagamento em preparação</strong><p>Este é um ambiente de demonstração. Nenhuma cobrança será realizada e o agendamento não será confirmado como pago.</p></div></div><button className="button button-primary full-button" onClick={onConfirm}>Simular fluxo de confirmação <ArrowRight size={16} /></button><p className="payment-disclaimer"><ShieldCheck size={14} /> Mercado Pago, Pix, cartão, e-mail e bloqueio automático de agenda dependem das credenciais de produção.</p></div>; }
function StepIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="step-intro"><span className="section-kicker">{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div>; }
function Confirmation({ preview, setLocation }: { preview: BookingPreview; setLocation: (path: string) => void }) { const { booking, readingName, publicCode, paymentStatus } = preview; return <div className="site-shell booking-shell"><SiteHeader /><main className="confirmation-page section-pad"><div className="confirmation-icon"><Check size={28} /></div><span className="section-kicker">PRÉ-RESERVA · {publicCode}</span><h1>Seu encontro com<br /><em>a Celeste está encaminhado.</em></h1><p className="confirmation-lede">Esta é uma confirmação de demonstração. A reserva real só assumirá o status confirmado após o pagamento validado.</p><div className="confirmation-card"><div><span>Leitura</span><strong>{readingName}</strong></div><div><span>Data e horário</span><strong>{booking.date ? new Date(`${booking.date}T12:00:00`).toLocaleDateString("pt-BR") : "—"} · {booking.time}</strong></div><div><span>Modalidade</span><strong>{booking.modality ? getModalityLabel(booking.modality) : "—"}</strong></div><div><span>Status</span><strong className="pending-status">{paymentStatus === "aguardando_pagamento" ? "Aguardando pagamento" : paymentStatus}</strong></div></div><div className="confirmation-actions"><button className="button button-primary" onClick={() => setLocation("/")}>Voltar para a Celeste <ArrowRight size={16} /></button><a className="button button-ghost" href="https://wa.me/5500000000000" target="_blank" rel="noreferrer">Falar pelo WhatsApp <MessageCircle size={16} /></a></div></main></div>; }
